### PR TITLE
Handle 201 status code received from API.

### PR DESCRIPTION
**Pull request by sergeyzenchenko**
The plugin is not working because currently runscope API responds with 201 code not 200.

### CODE REVIEW

**Comment by sergeyzenchenko** [comment]
fyi @garrettheel

**Comment by sergeyzenchenko** [comment]
up @skastel @frankstratton @mansilladev

**Comment by johnsheehan** [comment]
We'll take a look!

**Comment by johnsheehan** [comment]
We'll get a new release queued up. Thanks!

**Pull request merged**
